lists/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    # re_path(route=r'^new$', view=views.new_list, name='new_list'),
    re_path(route=r'^new$', view=views.NewList.as_view(), name='new_list'),
    # re_path(route=r'^(\d+)/$', view=views.view_list, name='view_list'),
    re_path(route=r'^(\d+)/$', view=views.ViewList.as_view(), name='view_list'),
    # re_path(route=r'^users/(.+)/$', view=views.my_lists, name='my_lists'),
    re_path(route=r'^users/(.+)/$', view=views.MyLists.as_view(), name='my_lists'),
    # re_path(route=r'^(\d+)/share$', view=views.share_list, name='share_list'),
    re_path(route=r'^(\d+)/share$', view=views.ShareList.as_view(), name='share_list'),
]

superlists/urls.py
# from django.contrib import admin
from django.urls import re_path, include

from lists import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # re_path('^$', views.home_page, name='home'),
    re_path(route=r'^$', view=views.HomePage.as_view(), name='home'),
    re_path(route=r'^api/', view=include('lists.api_urls')),
    re_path(route=r'^lists/', view=include('lists.urls')),
    re_path(route=r'^accounts/', view=include('accounts.urls')),
]

lists/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()

# Create your models here.
class List(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    _shared_with = models.ManyToManyField(User, related_name='lists_with_users')

    @staticmethod
    def create_new(first_item_text: str, owner: AbstractUser = None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    def get_absolute_url(self) -> str:
        return reverse(viewname='view_list', args=[str(self.pk)])
    
    @property
    def name(self) -> str:
        return self.item_set.first().text
    
    @property
    def shared_with(self):
        return ListSharedWithManager(list=self)
    

class ListSharedWithManager:
    def __init__(self, list: List) -> None:
        self.list = list
    
    def all(self):
        return self.list._shared_with.all()
    
    def add(self, email: str):
        user = User.objects.get(email=email)
        self.list._shared_with.add(user)


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=models.CASCADE, default='')

    class Meta:
        ordering = ('id',)
        unique_together = ('text', 'list')

    def __str__(self) -> str:
        return self.text

lists/forms.py
from django import forms
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError

from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR},
        }
    

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list: List, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self) -> None:
        try:
            self.instance.validate_unique()
        except ValidationError:
            self.add_error(field='text', error=DUPLICATE_ITEM_ERROR)
    

class NewListForm(ItemForm):
    def save(self, owner: AbstractUser = None) -> None:
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

lists/views.py
from typing import Any

from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, HttpResponseNotAllowed
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.generic import View, FormView, DetailView

from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm

User = get_user_model()

# Create your views here.
class HomePage(FormView):
    form_class = ItemForm
    template_name = 'home.html'

# def home_page(request: HttpRequest) -> HttpResponse:
#     return render(request, 'home.html', {'form': ItemForm()})

class ViewList(View):

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        list_ = get_object_or_404(klass=List, id=self.args[0])
        form = ExistingListItemForm(for_list=list_)
        if request.method == 'POST':
            form = ExistingListItemForm(for_list=list_, data=request.POST)
            if form.is_valid():
                form.save()
                return redirect(to=list_)
        return render(request=request, template_name='list.html', context={'list': list_, 'form': form})

# def view_list(request: HttpRequest, list_id: int) -> HttpResponse | HttpResponseRedirect:
#     list_ = List.objects.get(id=list_id)
#     form = ExistingListItemForm(for_list=list_)
#     if request.method == 'POST':
#         form = ExistingListItemForm(for_list=list_, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(to=list_)
#     return render(request=request, template_name='list.html', context={'list': list_, 'form': form})

class NewList(FormView):
    form_class = NewListForm
    template_name = 'home.html'

    def form_valid(self, form: NewListForm) -> HttpResponse:
        list_ = form.save(owner=self.request.user)
        return redirect(to=list_)
    
# def new_list(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
#     form = NewListForm(data=request.POST)
#     if form.is_valid():
#         list_ = form.save(owner=request.user)
#         return redirect(to=list_)
#     return render(request=request, template_name='home.html', context={'form': form})

class MyLists(View):

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        email = self.args[0]
        owner = get_object_or_404(klass=User, email=email)
        return render(request=request, template_name='my_lists.html', context={'owner': owner})
  
# def my_lists(request: HttpRequest, email: str) -> HttpResponse:
#     owner = User.objects.get(email=email)
#     return render(request=request, template_name='my_lists.html', context={'owner': owner})

class ShareList(View, LoginRequiredMixin):

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        list_ = get_object_or_404(klass=List, pk=self.args[0])
        email = request.POST.get('sharee')
        try:
            list_.shared_with.add(email=request.user.pk)
            list_.shared_with.add(email=email)
            return redirect(to=list_)
        except User.DoesNotExist:
            return HttpResponseBadRequest()


# @require_POST
# @login_required
# def share_list(request: HttpRequest, list_id: int) -> HttpResponseRedirect | HttpResponseBadRequest:
#     list_ = get_object_or_404(klass=List, pk=list_id)
#     email = request.POST.get('sharee')
#     try:
#         list_.shared_with.add(email=request.user.pk)
#         list_.shared_with.add(email=email)
#         return redirect(to=list_)
#     except User.DoesNotExist:
#         return HttpResponseBadRequest()

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>To-Do lists</title>
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/base.css">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">Superlists</a>
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <ul class="nav navbar-nav navbar-left">
                                <li><a href="{% url 'my_lists' user.email %}">My Lists</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="navbar-text">Logged in as {{ user.email }}</li>
                                <li><a href="#"><input type="submit" value="Log out" id="id_logout"></a></li>
                            </ul>
                        </form>
                    {% else %}
                        <form class="navbar-form navbar-right" method="post" action="{% url 'send_login_email' %}">
                            <span>Enter email to log in:</span>
                            <input class="form-control" name="email" type="text">
                            {% csrf_token %}
                        </form>
                    {% endif %}
                </div>
            </nav>
            {% if messages %}
                <div class="row">
                    <div class="col-md-8">
                        {% for message in messages %}
                            {% if message.level_tag == 'success' %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% else %}
                                <div class="alert alert-warning">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        {% block list_form %}
                            <form name="item_form" method="post" action="{% block form_action %}{% endblock %}">
                                {{ form.text }}
                                {% csrf_token %}
                                <div class="form-group has-error">
                                    {% if form.errors %}
                                        <div class="help-block">{{ form.text.errors }}</div>
                                    {% endif %}
                                </div>
                            </form>
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">{% block table %}{% endblock %}</div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">{% block extra_content %}{% endblock %}</div>
            </div>
        </div>

        <!-- <script src="/static/jquery-3.7.1.min.js"></script>
        <script src="/static/list.js"></script> -->

        {% block scripts %}
            <script>
                window.addEventListener('load', () => {
                    window.document.querySelector('input[name="text"]').addEventListener('input', () => {
                        let divHasError = window.document.querySelector('.has-error');
                        divHasError.hidden = true;
                    });
                });
            </script>
        {% endblock %}
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do List{% endblock %}

{% block table %}
    <table id="id_list_table" class="table"></table>
{% endblock %}

{% block extra_content %}
    <div id="id_list_owner">{{ list.owner.pk }}</div>

    <h2>Share this list</h2>
    <form action="{% url 'share_list' list.pk %}" method="post">
        {% csrf_token %}
        <input type="text" name="sharee" placeholder="your-friend@example.com">
    </form>

    <ul>
        <h2>The list use:</h2>
        {% for user in list.shared_with.all %}
            <div class="list-sharee">
                <li>{{ user.email }}</li>
            </div>
        {% endfor %}
    </ul>
{% endblock %}

{% block scripts %}
    <script>
        async function getItems() {
            let response = await fetch("{% url 'get_items' list.pk %}", {
                mode: "same-origin",
                method: 'GET',
            });

            if (response.status === 200) return await response.json();
        };

        async function postItem(formData) {
            let response = await fetch("{% url 'post_item' list.pk %}", {
                mode: "same-origin",
                method: 'POST',
                headers: {
                    'X-CSRFToken': window.csrftoken,
                },
                body: formData,
            });

            return response;
        };

        async function displayItems(data) {
            if (!data instanceof Array) return;
            // if (!data instanceof Object) return;
            if (data.length === 0) return;

            let table = window.document.querySelector('#id_list_table');
            table.innerHTML = '';

            // let keys = Object.keys(data);
            // for (let key of keys) {
            for (let i = 0; i < data.length; i++) {
                let td = window.document.createElement('td');
                // td.textContent = `${key}: ${data[key].text}`;
                td.textContent = `${i + 1}: ${data[i].text}`;

                let tr = window.document.createElement('tr');
                tr.append(td);

                table.append(tr);
            };
        };

        async function displayErrors(data) {
            if (!data instanceof Object) return;
            if (data.length === 0) return;
            
            let li = window.document.createElement('li');
            li.textContent = data['text'][0];

            let ul = window.document.createElement('ul');
            ul.className = 'errorlist';
            ul.append(li);
                
            let divHelpBlock = window.document.createElement('div');
            divHelpBlock.className = 'help-block'
            divHelpBlock.append(ul);

            let divHasError = window.document.querySelector('.has-error');
            divHasError.append(divHelpBlock);
            divHasError.hidden = false;
        };

        window.addEventListener('load', async () => {
            let result = await getItems();

            await displayItems(result);

            window.csrftoken = window.document.querySelector('input[name="csrfmiddlewaretoken"]').value;

            window.document.querySelector('input[name="text"]').addEventListener('input', () => {
                let divHasError = window.document.querySelector('.has-error');
                divHasError.hidden = true;
            });

            window.document.forms.namedItem('item_form').addEventListener('submit', async (event) => {
                event.preventDefault();

                let textInput = window.document.querySelector('input[name="text"]');

                let formData = new FormData();
                formData.append('text', textInput.value);

                let response = await postItem(formData);

                if (response.status === 201) {
                    textInput.value = '';

                    let result = await getItems();

                    await displayItems(result);
                } else {
                    let result = await response.json();

                    await displayErrors(result);
                };
            });
        });
    </script>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
<h2>{{ owner.email }}'s lists</h2>
<ul>
    {% for list in owner.list_set.all %}
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
    {% for list in owner.lists_with_users.all %}
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}